/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"
#include <unistd.h>
#include <stdio.h>

void *
mywrite_1_svc(message *argp, struct svc_req *rqstp)
{
	static char * result;

	write(STDOUT_FILENO, argp->contents, 10);

	return (void *) &result;
}

message *
getchar_1_svc(void *argp, struct svc_req *rqstp)
{
	static message  result;

	/*
	 * insert server code here
	 */

	return &result;
}
