/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->contents, ~0))
		 return FALSE;
	return TRUE;
}
