/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAM_NAME 0x20000001
#define PROGRAM_NAME 1

#if defined(__STDC__) || defined(__cplusplus)
#define increment 1
extern  int * increment_1(int *, CLIENT *);
extern  int * increment_1_svc(int *, struct svc_req *);
extern int program_name_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define increment 1
extern  int * increment_1();
extern  int * increment_1_svc();
extern int program_name_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
